### PR TITLE
Add template for mindmap to be exported to Beamer

### PR DESCRIPTION
**Pull request by jose1711**

### CODE REVIEW

**Comment by fnatter** [comment]
hi Jose,

I really like the idea of a latex beamer template. Please fix two things:

- when I export the unmodified template on Debian stable, and run pdflatex on it, I get:
```
Runaway argument?
{\frametitle {Frame with listings} 
! Paragraph ended before \beamer@@@checkoldframe was complete.
<to be read again> 
                   \par 
l.636 \end{frame}
                 }
```
Can you do it or shall I look into it? Is it a bug in the exporter?

You might also want to fix lacheck detected problems:
```
$ lacheck beamer.tex 
"beamer.tex", line 20: possible unwanted space at "{"
"beamer.tex", line 48: possible unwanted space at "{"
"beamer.tex", line 56: possible unwanted space at "{"
"beamer.tex", line 428: Fontspecifiers don't take arguments. "$\tt"
"beamer.tex", line 430: <- unmatched "\end{itemize}"
"beamer.tex", line 428: -> unmatched "math begin $"
"beamer.tex", line 445: <- unmatched "\end{frame}"
"beamer.tex", line 425: -> unmatched "\begin{itemize}"
"beamer.tex", line 445: <- unmatched "}"
"beamer.tex", line 424: -> unmatched "\begin{frame}"
"beamer.tex", line 456: Fontspecifiers don't take arguments. "$\tt"
"beamer.tex", line 458: Fontspecifiers don't take arguments. "$\tt"
"beamer.tex", line 549: <- unmatched "\end{document}"
"beamer.tex", line 424: -> unmatched "\begin{frame}"
"beamer.tex", line 549: <- unmatched "end of file beamer.tex"
"beamer.tex", line 424: -> unmatched "{"
"beamer.tex", line 549: <- unmatched "end of file beamer.tex"
"beamer.tex", line 47: -> unmatched "\begin{document}"
```
- please set the zoom to 100%, or something larger than 0.2x (too small on my system)

Many Thanks and Best Regards,
Felix

**Comment by jose1711** [comment]
hey felix, wrt runaway argument. it should work normally after merging of https://github.com/freeplane/freeplane/pull/111.

**Comment by jose1711** [comment]
zoom set to 100 % (commit amended)

**Comment by fnatter** [comment]
hi Jose,

I still get this with your template:
```
Runaway argument?
{\frametitle {Frame with listings} 
! Paragraph ended before \beamer@@@checkoldframe was complete.
<to be read again> 
                   \par 
l.605 \end{frame}
                 
? 
```

Here is the freeplane/src/external/resources/xslt/mm2latexbeamer_richcontent_1.3.x.xsl diff I applied
from your 111 PR:
```
--- a/freeplane/src/external/resources/xslt/mm2latexbeamer_richcontent_1.3.x.xsl
+++ b/freeplane/src/external/resources/xslt/mm2latexbeamer_richcontent_1.3.x.xsl
@@ -62,6 +62,7 @@ Modified; 14th February 2012: "figuresp" template extended to make compatible wi
 Modified_ 16th of June 2014: Compatibility issues with ##1.3.x## version of freeplane. 
        1- LaTeX equations are identified as  "FORMAT="latexPatternFormat" within the node info. We keep the "hook" option for backwards compatibility. Warning: LaTeX Format will be exclusivelly considered for formulas (it will create an "equation" environment). 
        2- Now there are more "hooks" because IMAGES can also be inserted as "hooks" therefore, the old equation filter "hook" has to be adjusted to the specific type "hook equation". Hooks with NAME=ExternalObject will be considered as images. 
+Modified: October 2018: Enable listings environment. (jose1711)
 
 Thanks to: Gorka Marcos and Myriam Alustiza for giving the xsl syntax support                    
 
@@ -93,7 +94,9 @@ See: http://freemind.sourceforge.net/
 \usepackage{url}
 \usepackage[T1]{fontenc}
 \usepackage[english]{babel}
-%\usepackage{listings}
+\usepackage{listings}
+\lstset{basicstyle={\ttfamily},
+basewidth={0.5em}}
 \RequirePackage{eurosym}
 \usepackage{hyperref}
 
@@ -225,7 +228,6 @@ See: http://freemind.sourceforge.net/
                <xsl:apply-templates/>
        </xsl:if>
        <xsl:if test="(count(ancestor::node())-2)=3"> <!-- We are starting a frame-->
-               <xsl:text>&#xD;{&#xD;</xsl:text>
                
                <xsl:if test="current()/attribute/@NAME = 'backgroundpicture' ">
                        <xsl:text>
@@ -299,7 +301,6 @@ See: http://freemind.sourceforge.net/
                                </xsl:otherwise>
                        </xsl:choose>
                        <xsl:text>&#xD;\end{frame}</xsl:text>
-                       <xsl:text>}</xsl:text>
                <xsl:apply-templates/>
        </xsl:if>
 </xsl:template>
@@ -705,3 +706,4 @@ See: http://freemind.sourceforge.net/
 
 </xsl:stylesheet>
 
+
```

Am I missing something? Could you investigate?

Many Thanks and Best Regards,
Felix

**Comment by jose1711** [comment]
sorry felix, my bad. the #111 PR has been incomplete. please try now with the updated xslt file

**Comment by fnatter** [comment]
@Jose: I will merge this now. Many thanks for the contribution!

**Pull request merged**
