### PR TITLE
Feature/decode at for exec and uri for edit

### PR DESCRIPTION
**Pull request by macmarrum**

### CODE REVIEW

**Comment by macmarrum** [comment]
Closing: PR against wrong master - was meant to be within own fork to do a mock internal review

**Comment by dpolivaev** [comment]
I want to suggest that we pair on this issue after 1.11.5 is released as stable.

**Comment by dpolivaev** [comment]
Hello @macmarrum, if the topic you raised is still relevant, now I have time to work on it.
Would you like to pair?

**Comment by macmarrum** [comment]
Hi @dpolivaev 
Thanks.
I have analyzed the topic and I believe it isn't feasible to decode URI for editing – I'll close this PR.
I'm about to create another PR, limited only to decoding #at for execution.
Please let me know in case you need to discuss it further.

**Pull request closed without merging**
