### PR TITLE
better mm2html.xsl

### PR DESCRIPTION
**Pull request by hokorobi**
fix indent
output image

### CODE REVIEW

**Comment by fnatter** [comment]
hello hokorobi,

>fix indent
>output image

thanks for your contribution to Freeplane.
Your changes look ok to me, but there is one thing:

    < 		MINDMAPEXPORTFILTER html;htm %xslt_export.html
    ---
    >     MINDMAPEXPORTFILTER html;htm HTML with image

'%xslt_export' is a translation key (results in i.e. "Html Dokument" in
German or "Documento HTML" in Spanish or ...). Your change has hardcoded
the "HTML with image" export filter name.

There are two solutions:

(1) Revert this change (i.e. keep '%xslt_export.html')

(2) If you want to create a separate exporter (like when there are use cases
when the user doesn't want to export images which I cannot think of):
- put the changes in mm2html_with_images.xsl and
- use MINDMAPEXPORTFILTER html;htm %xslt_export.html_with_images
- and add translations for xslt_export.html_with_images

What do you think?

Thanks and Best Regards,
Felix

**Comment by hokorobi** [comment]
Hello, Felixb.

Thank you for your comments.
I employ "(1)".

Best regards,
hokorobi

**Comment by fnatter** [comment]
hello hokorobi,

will you create a new pull request?

Best Regards,
Felix

**Comment by dpolivaev** [comment]
Usually new pull requests are not needed because all commits pushed to the branch by the request author are automatically added to the original request.

**Comment by dpolivaev** [comment]
So for instance this pull request consists of two commits, the original one and the new one

**Comment by hokorobi** [comment]
Thank you

**Pull request merged**
