### PR TITLE
Add gradle wrapper to project

### PR DESCRIPTION
**Pull request by inglor**
Gradle wrapper removes one step from developer's setup and Continuous Integration, more info on [docs]

With this the gradle dependency for distribution packages (-git versions) would be removed [freeplane-git Archlinux package]

[docs]: https://docs.gradle.org/current/userguide/gradle_wrapper.html
[freeplane-git Archlinux package]: https://aur.archlinux.org/packages/freeplane-git/

### CODE REVIEW

**Comment by dpolivaev** [comment]
Why should we add gradle wrapper? Nobody commits ant, maven or jdk binaries, so why is gradle different?

**Comment by inglor** [comment]
This would avoid questions such as #48 and as explained on the description the VCS packages for archlinux (not sure about debian) currently needs gradle as a make dependency. Apart from these, quoting the gradle docs:

> Most tools require installation on your computer before you can use them. If the installation is easy, you may think that’s fine. But it can be an unnecessary burden on the users of the build. Equally importantly, will the user install the right version of the tool for the build? What if they’re building an old version of the software?
The Gradle Wrapper (henceforth referred to as the “Wrapper”) solves both these problems and is the preferred way of starting a Gradle build.

**Comment by fnatter** [comment]
I am also not sure that this is helpful (unless gradlew would automatically use the gradle build
daemon, which would improve build times).
Debian/Ubuntu is not an argument, as gradle needs to be packaged separately, and cannot be downloaded.

Cheers and Best Regards,
Felix

**Comment by inglor** [comment]
@fnatter The gradle 3+ automatically enabled gradle daemon. The recommendation though for CI build is to have it disabled [1]

[1]: https://docs.gradle.org/current/userguide/gradle_daemon.html#when_should_i_not_use_the_gradle_daemon

**Comment by inglor** [comment]
PS: maven has a wrapper https://github.com/takari/maven-wrapper

**Comment by inglor** [comment]
Bump, this has been rebased against 1.6.x and using latest gradle which is much faster in incremental builds

**Pull request closed without merging**
