### PR TITLE
translation: [zh_CN] fix missing keys (translate me)

### PR DESCRIPTION
**Pull request by danix800**
For quick review:

- `+AddSelfConnectorAction.text=添加连接器样式`
- `+close=关闭`
- `+CopyMapStylesAction.text=从…复制导图样式`
- `+copyStyles=复制样式`
- `+defaultstyle.selection=选择节点`
- `+firstTimePdfExportWarning=为收集可用字体，首次导出可能需要较长时间。应用程序将在一段时间内无响应。`
- `-FollowLinkAction.text=打开超链接`  (not used in `en`)
- `+followed_map=目标导图: {0}`
- `+FollowLinkAction.text=跟随链接`
- `+followMindMap=跟随样式变更`
- `+latex=LaTeX`
- `+ManageFollowedMindMapAction.text=管理跟随导图`
- `+markdown=Markdown`
- `+markdown_editor=编辑Markdown`
- `+markdownPatternFormat=Markdown`
- `-NodeWidthAction.text=设定节点宽度限制...` (not used in `en`)
- `+open=打开`
- `+OptionPanel.add_emojis_to_icon_selector=添加表情包到图标选取器`
- `+OptionPanel.add_emojis_to_icon_toolbar=添加表情包到工具条`
- `+OptionPanel.add_emojis_to_menu=添加表情包到菜单`
- `+OptionPanel.CopiedImageSources.ANY=全部`
- `+OptionPanel.CopiedImageSources.ANY_ABSOLUTE_URL=从任何相对位置`
- `+OptionPanel.CopiedImageSources.ANY_HTTP_URL=从因特网(http, https)`
- `+OptionPanel.CopiedImageSources.NONE=无`
- `+OptionPanel.copyFormatToNewChild=复制样式到新子节点`
- `+OptionPanel.detailsContentType=节点明细`
- `+OptionPanel.enforceModalEditorDialogs=强制使用模态对话框`
- `+OptionPanel.enforceModalEditorDialogs.tooltip=非模态对话框对某些窗口管理器会有问题`
- `+OptionPanel.file_chooser_shows_special_folders=文件选取器中显示特殊文件夹`
- `+OptionPanel.file_chooser_shows_special_folders.tooltip=如果文件选取器很耗时可以禁用`
- `+OptionPanel.html_export_includes_colors=Html包含颜色`
- `+OptionPanel.indentTextOutput=缩进剪贴板文本`
- `+OptionPanel.keepSelectedNodeVisibleAfterZoom=缩放时保持所选节点可见`
- `+OptionPanel.markdown_disable_editor=禁用Markdown编辑器`
- `+OptionPanel.markdown_editor_font=Markdown编辑器字体`
- `+OptionPanel.markdown_editor_font_size=Markdown编辑器字体大小`
- `+OptionPanel.monitor_external_mind_map_file_changes=监视外部导图文件变更`
- `+OptionPanel.noteContentType=节点注解`
- `+OptionPanel.openLinksOnPlainClicks=单击打开节点链接`
- `+OptionPanel.openLinksOnPlainClicks.tooltip=此选项禁用时使用Ctrl键(MacOS的⌘)来打开链接`
- `+OptionPanel.separator.ContentTypes=内容类型`
- `+OptionPanel.separator.markdown=Markdown`
- `+OptionPanel.showLinkSpecificIcons=显示链接特定的图标`
- `+OptionPanel.simplyhtml.images_copied_by_editor=编辑器所复制图片`
- `+OptionPanel.text.use_control_click_on_icon=可通过点击图标选择器中的图标时按下Ctrl键来给图标选择器赋快捷键。`
- `+OptionPanel.text.use_control_click_on_menu_item=除非在Mac上，你还可以通过点击菜单项时按下Ctrl键。`
- `+OptionPanel.zoomAroundSelectedNode=缩放时保持节点位置`
- `+reload_mindmap_after_external_change=导图文件被另一个程序修改，是否重新加载？`
- `-remove_shortcut_title=移除快捷键`  (not used in `en`)
- `+replaceStyles=替换样式`
- `+stylesUpdated=从{1}更新了{0}个导图样式`
- `+unfollow=取消跟随`

### CODE REVIEW

**Comment by dpolivaev** [comment]
Thanks

**Comment by danix800** [comment]
You're welcome. I'm a Chinese speaker so if any new releases come out or any time new translation review or fixing  is needed you can mail me directly, and I'll see what I can do.

By the way, I'm a new freeplane user. I'm reading the source code and I'm considering adding a mini-map to the bottom-right main map view. Is that a good idea? I think such a mini-map would be convenient for navigating large maps.

Any suggestions?

**Comment by danix800** [comment]
Maybe look like this:

Screenshot from 2021-05-13 23-29-06

**Comment by dpolivaev** [comment]
Great, I really like and appreciate any contributions. 
I would probably put the mini-map in a non modal dialog so that users can change its position and size.
If you want to get in touch with the community and get feedback from our active users write a post to https://sourceforge.net/p/freeplane/discussion/758437/ 
If you need any help from me related to the project setup, debugging or code don't hesitate to ask me questions.
You can also open an empty pull request write now so that we can communicate about all related issues as your code grows.

**Comment by ldmpub** [comment]
Hi,

+1 👍 ; adding a minimap to Freeplane would be a really good idea.

I personally suggest following "sub features":

**1. minimap should automaticaly "zoom" the map to fully fit in a minimap area** (minimap area form is automatically computed to square or rectangle)
**2. drag & drop of minimap borders should allow to resize minimap area** (and updates minimap display accordingly ; square or rectangle minimap form is not free)
**3. minimap should be a perfect mirror of map for "folding state only"** / other "display actions" done in main map (like changing zoom level or moving the main map) do not affect minimap
4. only 2 actions are available in minimap area:
**. enable/disable a magnifying glass**. Details when option enabled: a magnifying glass is sticked to the mouse position, zoom is made on minimap "mouse over" (hope not to have to introduce a zoom level for this magnifying glass 🤔 just a "custom size" of the magnifying glass). Magnifying glass appears or disappears depending on mouse position: in or out of minimap area. Suggestion: enable/disable of magnifying glass can be done either with an button icon (a kind of toolbar icon) or by mouse hold down button (code only one of these 2 behaviors or both of them?)
. already suggested: **click on minimap should open / close clicked node on both maps** but the mouse position should not be automatically moved to main map! (mouse pointer is staying at its clicked position in minimap).

- option: **minimap can be moved** (placed in 4 corners or floating).

What do you think? Don't hesitate to react to above suggestions.
I would be your first tester and 2d user 😀.

**Comment by danix800** [comment]
Hi @ldmpub , please take a look at https://github.com/freeplane/freeplane/pull/197 and give it a try if possible!

**Comment by ldmpub** [comment]
Hi @danix800 , thanks for your message and your great work 👍.
I'm sorry but I'm not able to build freeplane by myself 😪.

Please warn me (here ?) when a freeplane "preview build" with your minimap feature will be available for test. It should (automatically?) be published in folder https://sourceforge.net/projects/freeplane/files/freeplane%20preview/ ...

**Pull request merged**
