### PR TITLE
Added Linux Desktop Entry

### PR DESCRIPTION
**Pull request by freeman42x**
Solution for: https://github.com/freeplane/freeplane/issues/95

### CODE REVIEW

**Comment by dpolivaev** [comment]
How can I test it under Ubuntu?

**Comment by freeman42x** [comment]
@dpolivaev I tested it under NixOS.

To test it right now is a bit complicated since it has not been packaged yet completely as the package is relying on this .desktop changes also. If you really want to test it you could install Nix package manager under Ubuntu https://nixos.org/nix/ , https://nixos.org/nix/download.html and then
`git clone git@github.com:razvan-panda/nixpkgs.git` and checkout the `freeplane` branch. While being in the cloned repository root run `nix-env -f . -iA freeplane`. This should install freeplane and it should be available to launch via terminal or from the Ubuntu menu.

I'll try to see if I don't have any Ubuntu VM to test on it also.

**Comment by dpolivaev** [comment]
All right. I shall merge it now and I shall move the file to another directory at the weekend.
I would like to change the top level directory structure a bit: currently your file would better fit into directory `freeplane/freeplane_framework/linux-resources` , but I think it would be even better to create a new directory `freeplane/freeplane-resources` and to move some of stuff under `freeplane/freeplane_framework` there. Please look into current freeplane/freeplane_framework and comment what you think about it.

**Comment by freeman42x** [comment]
I had a look but it is not clear to me where it should go. I placed it under freeplane/resources since that seemed a good place to place it. If you change its location I'll need to update the Nix expression after that. That's fine as long as you can structure the project better.

**Pull request merged**
