### PR TITLE
Enable listings environment in beamer export template

### PR DESCRIPTION
**Pull request by jose1711**

### CODE REVIEW

**Comment by dpolivaev** [comment]
@fnatter could you please review this PR

**Comment by igor-go** [comment]
As listings are to format code, this could be done just by invoking this environment from the written text. Do you think that we should create a kind of node attribute to enable it directly?,

I'll add the listings package load in the next version's header.

**Comment by jose1711** [comment]
i don't think a separate node type is necessary. anyway the curly brackets had also to be removed - otherwise the pdf could not by typeset.

**Comment by fnatter** [comment]
hello Igor,

could you please make an upstream release for inclusion in Freeplane 1.7.x?

Thanks and Best Regards!
Felix

**Pull request merged**
