### PR TITLE
decode at for execution and uri for editing

### PR DESCRIPTION
**Pull request by macmarrum**

### CODE REVIEW

**Comment by dpolivaev** [comment]
I am not sure when the strings are encoded and when they are not. Actually, in Java URI is always encoded but for URL it depends. Therefore I am not sure if the fix is needed and if it never makes any trouble.

**Comment by macmarrum** [comment]
How can I help to increase your level of confidence?

**Comment by dpolivaev** [comment]
Hello, I am sorry for responding to you when I actually was having no time myself.

Could you please explain the reasons behind each change you made? 

Seeing only the changes and without understanding the cases behind it I can not see which problem or problems are solved and if the solution is correct. If it is a bug fix please describe the bugs.

For me, it is also not clear why the complete text is always URL-encoded, that you should decode it before showing it to the user, and when it is encoded again.

**Comment by macmarrum** [comment]
I have analyzed the cases some more and realized I've made some assumptions, therefore I am withdrawing this PR. I will create a new one.

**Pull request closed without merging**
